return {
	{
		"williamboman/mason.nvim",
		opts = {
			ensure_installed = {
				"bash-debug-adapter",
				"bash-language-server",
				"black",
				"docker-compose-language-service",
				"dockerfile-language-server",
				"eslint-lsp",
				"flake8",
				"goimports",
				"golangci-lint",
				"gopls",
				"gotests",
				"hadolint",
				"json-lsp",
				"markdownlint",
				"mypy",
				"pylint",
				"pyright",
				"python-lsp-server",
				"ruff",
				"ruff-lsp",
				"rust-analyzer",
				"shellcheck",
				"shfmt",
				"sqlfmt",
				"terraform-ls",
				"tflint",
				"tfsec",
				"yaml-language-server",
			},
		},
	},
}
