# plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-copycat"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-open"
set -g @plugin 'dracula/tmux'

# use xterm-256color for pretty colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',*-256color:Tc'

# mouse support
set -g mouse on

# window index stars at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# open new split in current path
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# theme options
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-plugins "time"


# load tmux package manager
run -b "~/.tmux/plugins/tpm/tpm"
